version: "3.9"
services:
  tutake:
    build: .
    user: '1000'
    ports:
      - "49191:5000"
    volumes:
      - /etc/localtime:/etc/localtime
      - ./docker/docker-config.yml:/tutake/config.yml
      - /opt/tutake/tutake-data:/tutake/data
      - ./tutake:/tutake/tutake
      - ./entrypoint.py:/tutake/entrypoint.py
    entrypoint: [ 'python','entrypoint.py' ]