version: "3.9"
services:
  tutake:
    build: .
    user: '1000'
    volumes:
      - /etc/localtime:/etc/localtime
      - ./docker/docker-config.yml:/tutake/config.yml
      - /home/ubuntu/tutake-data:/tutake/data
    entrypoint: [ 'python','entrypoint.py' ]