version: "3.9"
services:
  tutake:
    build: .
    user: '1000'
    ports:
      - "49191:5000"
    volumes:
      - /etc/localtime:/etc/localtime
      - ./docker/docker-config.yml:/tutake/config.yml
      - /home/ubuntu/tutake-data:/tutake/data
      - /home/ubuntu/docker/tutake/tutake:/tutake/tutake
    entrypoint: [ 'python','entrypoint.py' ]